### ISSUE TITLE
Commit and tag version für .NET Projekte

### ISSUE THREAD

**Issue by christianbernds** [process-engine/ci_tools#54]
## Description

In der aktuellen Alpha-Version werden die CI-Tools für .NET-Projekte erweitert.
Hierfür muss auch der "Commit and tag Version"-Command angepasst werden, da dieser zur Zeit nur package.json-Dateien mittels `git add` hinzufügt und pusht.

https://github.com/process-engine/ci_tools/blob/develop/src/commands/commit-and-tag-version.ts#L103

**Comment by rrrene** [comment]
Fixed in `v3.0.0`
