### ISSUE TITLE
Publizieren von Tags trotz Dry-Run

### ISSUE THREAD

**Issue by christianbernds** [process-engine/ci_tools#55]
## Description

Der Dry-Run des "Commit and tag Version"-Command führt trotzdem zu einem tagen und pushen nach GitHub.

> ci_tools commit-and-tag-version --mode=dotnet --dry
 
[setup-git-and-npm]	Did not find env variables GH_USER and GH_TOKEN, leaving Git config as is.
[commit-and-tag-version]	isDryRun: true
[commit-and-tag-version]	isForced: false

[commit-and-tag-version]	packageVersion: 1.0.0-alpha.1
[commit-and-tag-version]	packageVersionTag: v1.0.0-alpha.1
[commit-and-tag-version]	branchName: feature/testGithubActions

[commit-and-tag-version]	|>>> git config user.name
[commit-and-tag-version]	| xxx
[commit-and-tag-version]	|
[commit-and-tag-version]	|>>> git config user.email
[commit-and-tag-version]	| xxx
[commit-and-tag-version]	|
>> git push origin feature/testGithubActions
To github.com:5minds/xxx.git
   f508219..88c4834  feature/testGithubActions -> feature/testGithubActions
>> git push --tags
To github.com:5minds/xxx.git
 * [new tag]         v1.0.0-alpha.1 -> v1.0.0-alpha.1
[commit-and-tag-version]	Commited package.json with version 1.0.0-alpha.1 and tagged that commit as "v1.0.0-alpha.1"

**Comment by rrrene** [comment]
Fixed in `v3.0.0`
