### ISSUE TITLE
♻️ `xml2js` statt `xml2json` nutzen

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/ci_tools#56]
## Description

Warum das Ganze?

1. `xml2js` hat mehr als 100x so viele Downloads wie `xml2json`
Vgl: [xml2js](https://www.npmjs.com/package/xml2js) vs [xml2json](https://www.npmjs.com/package/xml2json)
Ich denke die Zahlen sprechen hier für sich. 

Da wir u.a. bei `addict-ioc` vs `inversify` damit argumentieren, dass es stets klüger ist, bereits bewährte Pakete gegenüber kleineren, bzw. unbekannteren zu bevorzugen, wäre es imho auch hier angebracht, das beliebtere und bewährte Paket zu benutzen.

2. `xml2json` verwendet einige veraltete und nicht mehr unterstützte Dependencies, die sich dann in den ganzen Stack installieren würden. Siehe Installations Log (passiert alles nicht mit dem Nutzen von `xml2js`)`:

![Bildschirmfoto 2020-03-03 um 10 12 00](https://user-images.githubusercontent.com/15343316/75760379-7a05b400-5d37-11ea-9896-6cf6b31a2782.png)

3. `xml2js` hat sich als Parser bereits in der ProcessEngine bewährt, wo es für das Parsing der `.bpmn` files benutzt wird. Hier gab es nie irgendwelche Schwierigkeiten.

Nachteil des Ganzen:

`xml2js` läuft async, d.h. es muss mit Callbacks oder Promises gearbeitet werden (i.e. `await xmlParser.parseStringPromise(contents);` oder `xmlParser.parseString(contents, callbackFunc);`). 

Der Großteil der CI_Tools läuft synchron, ich bin nicht sicher, ob das ein Pattern ist, das man brechen kann?

**Comment by rrrene** [comment]
@ElRaptorus Du hast natürlich mit allem Recht.

Das mit der Asynchronität sollte kein Hindernis sein :+1:
