### ISSUE TITLE
Release Notes sollten Änderungen zwischen letzter und aktueller Beta zeigen

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/ci_tools#74]
## Beschreibung

Aktuell zeigen die generierten Release Notes alle Änderungen, die sich seit dem letzten Stable Release ergeben haben. 

Ich denke es wäre für Beta Releases aber auch ganz nützlich zu sehen, welche Änderungen sich seit der letzten Beta ergeben haben.

Aktuell muss ich stets die Release Notes der aktuellen und der vergangenen Beta selbst raussuchen und händisch gegenüberstellen. 

Das kann bei Iterationen, in denen eine Vielzahl von Alphas produziert wird, schnell mal unangenehm werden. 
Besonders wenn während des Feature Freezes bereits Alphas für die _nächste_ Version erstellt wurden.

## Lösungsvorschlag

Für Beta Releases könnten neben dem Standard Changelog, welches die Änderungen seit dem letzten Stable Release zeigt, noch eine weitere Sektion eingeführt werden, die nur die Änderungen seit dem letzten Beta Release aufführt.

Könnte man dann "Changes since the last Beta" o.ä. betiteln.

Wenn es noch kein Beta Release für die entsprechende Version gegeben hat, kann man die Sektion weg lassen.

Könnte z.B. so aussehen:

![musterchangelog](https://user-images.githubusercontent.com/15343316/87563049-131de180-c6bf-11ea-974a-06238bd06644.png)

Ich denke insgesamt würde uns das auch die Kommunikation von neuen Features an unsere Anwender immens erleichtern.

**Comment by rrrene** [comment]
Großer Fan der Idee! Hatte da letztes Jahr schonmal drüber nachgedacht und eine ähnliche Idee verworfen, weil es mir dann doch zu "lyrisch" war mit dem vielen Text.

Ich frage mich, ob wir das bei der Umsetzung noch ein bisschen straffer hinkriegen, ohne den Informationsgehalt zu verlieren (und ohne, dass die Release Notes 50% länger werden).

Vielleicht in diese Richtung:

![image](https://user-images.githubusercontent.com/311914/87564849-2fbb1900-c6c1-11ea-9ce8-bc04312ca0f7.png)

Da wir in der Regel 4-5 Betas haben (wenn wir den Releaseprozess wieder im Normalbetrieb haben), würde das so übersichtlich bleiben und alles mitteilen, was man braucht (und zusätzlich auf einen Blick die Frage beantworten "Oh, wann ist das denn dazu gekommen?").

Meinungen?

**Comment by ElRaptorus** [comment]
Deine Version gefällt mir besser. :+1:

**Comment by moellenbeck** [comment]
Was @ElRaptorus sagt 😎
